# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  languageName: English
  weight: 1
  menu:
    main:
      - name: Bio
        url: /
        weight: 10
      - name: Publications
        url: /publication
        weight: 11
      - name: Presentations
        url: /presentations
        weight: 12

ja:
  languageCode: ja
  languageName: 日本語
  weight: 2
  menu:
    main:
      - name: 自己紹介
        url: /
        weight: 10
      - name: 論文
        url: /publication
        weight: 11
      - name: 発表
        url: /presentations
        weight: 12
